# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-17 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170417_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSCodeSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(default='', max_length=64)),
                ('code', models.CharField(default='', max_length=64)),
                ('uptime', models.DateTimeField(auto_now=True, verbose_name='\u6570\u636e\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
